/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceCocineroServidorPedidos.h"


void
prog_cocineros_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	info_cocinero  registrar_cocinero_1_arg;
	bool_t  *result_2;
	int  notificar_completado_1_arg;
	pedido_asignado  *result_3;
	int  obtener_proximo_pedido_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG_COCINEROS, VER_COCINEROS_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrar_cocinero_1(&registrar_cocinero_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = notificar_completado_1(&notificar_completado_1_arg, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = obtener_proximo_pedido_1(&obtener_proximo_pedido_1_arg, clnt);
	if (result_3 == (pedido_asignado *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_cocineros_1 (host);
exit (0);
}
