/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "InterfaceCocineroServidorPedidos.h"

bool_t
xdr_info_cocinero (XDR *xdrs, info_cocinero *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estado))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pedido_asignado (XDR *xdrs, pedido_asignado *objp)
{
	register int32_t *buf;

	 if (!xdr_nodo_hamburguesa (xdrs, &objp->hamburguesa))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_pedido))
		 return FALSE;
	return TRUE;
}
