/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceClienteServidorPedidos.h"
#include "InterfaceServidorPedidosServidorDisplay.h"
#include <stdbool.h>



int cantidadUsuariosFila = 0;
cocinero vectorCocineros[3];
nodo_hamburguesa filaVirtual[10];

int consultarNumeroCocineroDisponible()
{
	int posicion = -1;
	for (int i = 0; i < 3; i++)
	{
		if (vectorCocineros[i].ocupado == false)
		{
			posicion = i;
			break;
		}
	}
	return posicion;
}

void notificar_cocineros_1()
{
	CLIENT *datosConexion;
	void  *result_1;
	char ipServidor[10];
	strcpy(ipServidor,"localhost");
	notificacion  objNotificacion;

#ifndef DEBUG
//Obtener la ubicacion dle servidor display
	datosConexion = clnt_create (ipServidor, notificar_cocineros, notificar_cocineros_version, "udp");
	if (datosConexion == NULL) {
		clnt_pcreateerror (ipServidor);
		exit (1);
	}
#endif  /* DEBUG */
	for(int i =0; i<3; i++){
		objNotificacion.cocineros[i].noCocinero=vectorCocineros[i].noCocinero;
		objNotificacion.cocineros[i].ocupado=vectorCocineros[i].ocupado;
		objNotificacion.cocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra=vectorCocineros[i].objHamburguesaAPreparar.cantidadIngredientesExtra;
		strcpy(objNotificacion.cocineros[i].objHamburguesaAPreparar.nombreHamburguesa,
		vectorCocineros[i].objHamburguesaAPreparar.nombreHamburguesa);
		objNotificacion.cocineros[i].objHamburguesaAPreparar.tipoHamburguesa=vectorCocineros[i].objHamburguesaAPreparar.tipoHamburguesa;
	}
	objNotificacion.cantidadUsuariosFilaVirtual=cantidadUsuariosFila;
	//enviar la notificacion
	result_1 = enviarnotificacion_1(&objNotificacion, datosConexion);
	if (result_1 == (void *) NULL) {
		clnt_perror (datosConexion, "call failed");
	}
#ifndef DEBUG
//eliminar recursos utilizados en la conexion
	clnt_destroy (datosConexion);
#endif   /* DEBUG */
}

int *generarturno_1_svc(nodo_hamburguesa *argp, struct svc_req *rqstp)
{
	static int result;
	int posicion = consultarNumeroCocineroDisponible();
	printf("\n");
	printf("\n Hamburguesa a preparar");
	printf("\n Nombre hamburguesa: %s", (*argp).nombreHamburguesa);
	printf("\n Tipo hamburguesa: %d", (*argp).tipoHamburguesa);
	printf("\n Cantidad de ingredientes extra: %d", (*argp).cantidadIngredientesExtra);
	if (posicion == -1)
	{
		printf("\n Los cocineros se encuentran ocupados");
		filaVirtual[cantidadUsuariosFila] = *argp;
		cantidadUsuariosFila++;
		printf("\n La hamburguesa se agrego a la fila virtual");
	}
	else
	{
		printf("\n El cocinero en la posicion %d esta libre y se asignara a la  hamburguesa con nombre %s",(posicion+1),(*argp).nombreHamburguesa);
		vectorCocineros[posicion].ocupado=true;
		vectorCocineros[posicion].objHamburguesaAPreparar=*argp;
	}
	result = cantidadUsuariosFila;
	notificar_cocineros_1();
	printf("\n");
	return &result;
}
/** 
// Cocinero 
// Registrar
int *registrar_cocinero_1_svc(int *id_cocinero, struct svc_req *req) {
    static int resultado;
    if (*id_cocinero < 1 || *id_cocinero > 3) {
        resultado = 0; // ID inválido
    } else if (cocineros[*id_cocinero - 1].ocupado) {
        resultado = 0; // ID ya en uso
    } else {
        cocineros[*id_cocinero - 1].ocupado = true; // Marcar como ocupado (aunque no tenga pedido aún)
        resultado = 1; // Éxito
    }
    return &resultado;
}
// Notificar pedido terminado
bool *notificar_pedido_terminado_1_svc(int *id_cocinero, struct svc_req *req) {
    static bool resultado;
    if (*id_cocinero < 1 || *id_cocinero > 3) {
        resultado = false; // Error: ID inválido
    } else {
        // Liberar al cocinero y asignar nuevo pedido de la fila (si existe)
        liberar_cocinero(*id_cocinero);
        resultado = true;
    }
    return &resultado;
}
**/