/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "InterfaceCocineroServidorPedidos.h"
#include <stdio.h>
#include <stdlib.h> 

void autorizar_cocineros_1(char *host)
{
	CLIENT *clnt;
	int  *result_validarCocinero;
	int  id_cocinero;
	int  *result_terminarPedido;

	#ifndef	DEBUG
	clnt = clnt_create(host, autorizar_cocineros, autorizar_cocineros_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	#endif	/* DEBUG */
	printf("\n =====PANEL-COCINERO=====");
	printf("\n Ingrese el id del cocinero: ");
	scanf("%d", &id_cocinero);
	id_cocinero = id_cocinero;
	printf("\n\n");
	result_validarCocinero = seleccionaridcocinero_1(&id_cocinero, clnt);
	if (result_validarCocinero == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(*result_validarCocinero == 0){
		printf("\n\nEl id del cocinero no es valido o ya esta en uso");
	}
	else{
		printf("\n\nEl id del cocinero fue registrado con exito");
	}	
	while(1){
		int opcion=-1;
		printf("\n =====MENU-COCINERO=====");
		printf("\n\n");
		printf("\n 1, Terminar pedido");
		printf("\n 0. salir");
		printf("\n\n");
		scanf("%d", &opcion);
		if(opcion == 1){
			result_terminarPedido = terminarpedido_1(&id_cocinero, clnt);
			if (result_terminarPedido == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			if(*result_terminarPedido == 0){
				printf("\n\nNo hay pedidos pendientes");
			}
			else{
				printf("\n\nEl pedido fue terminado con exito");
			}
		}
		else if(opcion == 0){
			printf("\n\nCocinero saliendo del sistema");
			break;
		}
	}
	clnt_destroy (clnt);
}

int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];


	autorizar_cocineros_1(host);
	
exit (0);
}